---
- name: Ensure homebrew-cask repositories tapped
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_cask_repositories | default([]) }}"
  when: homebrew_cask_repositories

- name: Update homebrew
  homebrew: update_homebrew=yes

- include: ricty.yml

- name: Ensure the homebrew cask packages installed
  homebrew_cask:
    name={{ item.name }}
    state={{ item.state | default('present')}}
  with_items: "{{ homebrew_cask_packages | default([]) }}"
  when: homebrew_cask_packages

