---
- name: Ensure homebrew repositories tapped
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_repositories
  when: homebrew_repositories

- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Ensure the packages installed
  homebrew:
    name={{ item.name }}
    state={{ item.state | default('latest')}}
    install_options={{ item.install_options | default(omit) }}
  with_items: homebrew_packages
  when: homebrew_packages

- include: ricty.yml
